### ISSUE TITLE
usb-to-RS485?

### ISSUE THREAD

**Issue by pungineering101** [ChaseDurand/Pool-Pi#10]
I really like the work you've done on this, and I'm going to adapt it for my system.  What are your thoughts on using a USB-to-RS485 adapter (something like https://www.amazon.com/USB-RS485-Applications-Communication-Requirement/dp/B081NBCJRS) to replace all the custom hardware?  

It seems like it would simplify the hardware design, and with a Pi Zero, it could be small enough to put right into my existing pool control box.  It seems like the only major changes would be in https://github.com/ChaseDurand/Pool-Pi/blob/master/src/model.py, to add a USB interface, and these code changes could potentially be simplified with something like pyUSB?

I'm going to tinker with it, and see what I come up with, and I'll share the results.

**Comment by ChaseDurand** [comment]
Hello!

I haven't used an adapter like that before or done any reading/writing to the pi's usb port, but in theory it should work. You would also need a micro usb male to usb A female adapter.

I like the idea of fitting it into the existing pool box! If I had to redo this I would have gone that route (assuming the metal enclosure doesn't attenuate the wifi signal too much).

Keep me updated with how it goes!
