### ISSUE TITLE
Manual reconnect required after power reset

### ISSUE THREAD

**Issue by ChaseDurand** [ChaseDurand/Pool-Pi#2]
The current hardware configuration requires pool-pi to be disconnected prior to the OEM unit power up. I suspect the OEM unit has a startup sequence involving the serial bus that the pool-pi is interrupting in its initial state (prior and during the OS boot). This causes the OEM unit to go into [Communication Err 1](https://github.com/ChaseDurand/Pool-Pi/blob/f952f5b3a177759a52cac1e1462e64a3c5e80093/docs/SETUP.md?plain=1#L84).

The root cause of the issue is hard to determine because it occurs at power up- before the pi (and therefore monitoring of the serial bus) is available.

This issue is a pain from a user perspective because it requires being physically present at the panel- which is counter to this project's purpose.

A solution might involve adding a pull up/down resistor to the RS485 DE and ~RE pins to ensure its default state is receiving to prevent interrupting any startup messages.

**Comment by rpaldrich** [comment]
Hmmm -- could you just input some sort of boot delay on the RPI?, or service delay for the pool.pi service? Ostensibly the only time the RPI would be booting would be if the aqualogic lost power, right?, and so anytime the RPI is rebooting one could assume that the aqualogic is also rebooting? 

Or does the RS485 converter itself cause the problem?
