### ISSUE TITLE
Non pi, non serial (sockets)

### ISSUE THREAD

**Issue by smith288** [ChaseDurand/Pool-Pi#9]
I really like this project and all that but was curious if there was a potential for choosing between serial and tcp sockets.  I have the EW11 RS485 -> Wifi adapter and was curious if the code here could easily be manipulated to use tcp sockets or is the code not abstracted enough to be able to handle such an option. 

Im not sure if it's the EW11 latency or swilson's aqualogic code that is the issue but my toggles are extremely erratic and non responsive most of the time.

https://github.com/swilson/aqualogic

Thanks!

**Comment by smith288** [comment]
Actually, I was able to make it socket specific with my own tweaks so kudos on your code being abstract enough to allow it.

**Comment by ChaseDurand** [comment]
This looks great! I'm glad you were able to get it working. I appreciate you making your changes public too!

**Comment by smith288** [comment]
> This looks great! I'm glad you were able to get it working. I appreciate you making your changes public too!

It’s been pretty fun to hack on. Never written a flask web app either so I was learning. Still am. Trying to make the templates a bit more modular.
